name: root
channels:
  - conda-forge
dependencies:
  - jupyterhub
  - bokeh
  - bqplot
  - cartopy=0.16.0
  - cdo
  - click
  - cython
  - cytoolz
  - dask
  - dask-ml
  - dask-kubernetes
  - datashader
  - depfinder
  - distributed
  - esmpy
  - fastparquet
  - fusepy
  - pyviz/label/dev::holoviews
  - gcsfs
  - pyviz/label/dev::geoviews
  - pyviz/label/dev::hvplot
  - intake::intake
  - intake::intake-xarray
  - ipywidgets
  - ipyleaflet
  - jedi
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - holoviews
  - libsodium
  - lz4
  - matplotlib
  - metpy
  - msgpack-python
  - nb_conda_kernels
  - nbserverproxy
  - netcdf4
  - nomkl
  - numba
  - numcodecs
  - numpy
  - pandas
  - pyviz/label/dev::panel
  - pygam
  - python-blosc
  - python-graphviz
  - pynio
  - pyzmq
  - rasterio
  - s3fs
  - scipy
  - scikit-image
  - scikit-learn
  - toolz
  - tqdm
  - tornado=5.1
  - umap-learn
  - utide
  - xarray
  - xesmf
  - xgcm
  - zarr
  - zict
