pangeo:
  jupyterhub:
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://web-public-ooi-prod-dask-gateway"
    scheduling:
      userPlaceholder:
        enabled: true
        replicas: 4
        resources:
          requests:
            cpu: 1.6
            memory: 5G
          limits:
            cpu: 3.2
            memory: 10G
    proxy:
      https:
        enabled: true
        hosts:
          - ooi.pangeo.io
        letsencrypt:
          contactEmail: tjcrone@gmail.com
      service:
        annotations: {'service.beta.kubernetes.io/azure-load-balancer-resource-group': 'ooi-pangeo'}
        loadBalancerIP: 23.96.23.164
  dask-gateway:
    webProxy:
      service:
        loadBalancerIP: 13.90.198.187
    schedulerProxy:
      service:
        loadBalancerIP: 40.76.63.49
