daskhub:
  jupyterhub:
    hub:
      # Reduce requests on staging hub since it is rarely used!
      resources:
        requests:
          cpu: 0
          memory: 0G
        limits:
          cpu: 0.5
          memory: 1G
      #extraEnv:
      #  OAUTH_CALLBACK_URL: "https://staging.aws-uswest2.pangeo.io/hub/oauth_callback"
    scheduling:
      userPlaceholder:
        enabled: false
    proxy:
      https:
        enabled: true
        hosts:
          - staging.ooi.pangeo.io
        letsencrypt:
          contactEmail: tjcrone@gmail.com
      service:
        annotations: {'service.beta.kubernetes.io/azure-load-balancer-resource-group': 'ooi-pangeo'}
        loadBalancerIP: 13.92.63.24

metrics:
  enabled: true

prometheus-operator:
  grafana:
    server:
      domain: "grafana.staging.aws-uswest2.pangeo.io"
    ingress:
      hosts:
        - "grafana.staging.aws-uswest2.pangeo.io"
