pangeo:
  jupyterhub:
    proxy:
      https:
        enabled: true
        hosts:
        - staging.ooi.pangeo.io
        letsencrypt:
          contactEmail: tjcrone@gmail.com
      service:
        annotations: {'service.beta.kubernetes.io/azure-load-balancer-resource-group': 'ooi-pangeo'}
        loadBalancerIP: 13.92.63.24
