pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - hydro.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
    hub:
      service:
        loadBalancerIP: 104.154.138.46
