pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - hydro.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
      service:
        loadBalancerIP: 104.154.138.46
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hydro.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "tls://scheduler-public-hydro-prod-dask-gateway:8786"
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://web-public-hydro-prod-dask-gateway"
