pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - staging.hydro.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
      service:
        loadBalancerIP: 35.238.0.56
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
