homeDirectories:
  nfs:
    # Output from gcloud beta filestore instances describe dev-home --location=us-central1-b
    serverIP: 10.171.161.186
jupyterhub:
  proxy:
    https:
      hosts:
      - dev.pangeo.io
      letsencrypt:
        contactEmail: dludwig@anaconda.com
    service:
      loadBalancerIP: 35.192.110.1

