distributed:
  logging:
    bokeh: critical

  dashboard:
    link: /user/{JUPYTERHUB_USER}/proxy/{port}/status

  admin:
    tick:
      limit: 5s

kubernetes:
  worker-template:
    metadata:
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: dask-worker
      restartPolicy: Never
      containers:
      - args:
          - dask-worker
          - --nthreads
          - '2'
          - --no-bokeh
          - --memory-limit
          - 7GB
          - --death-timeout
          - '60'
        image: ${JUPYTER_IMAGE_SPEC}
        name: dask-${JUPYTERHUB_USER}
        resources:
          limits:
            cpu: "1.75"
            memory: 7G
          requests:
            cpu: 1
            memory: 7G
        volumeMounts:
          - name: nfs
            mountPath: /home/jovyan
            subPath: "nasa.pangeo.io/home/${JUPYTERHUB_USER}"
        nodeSelector:
          k8s.io/cluster-autoscaler/node-template/label/spot: "true"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: home-nfs



labextension:
  factory:
    module: dask_kubernetes
    class: KubeCluster
    args: []
    kwargs: {}
