daskhub:
  jupyterhub:
    scheduling:
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    singleuser:
      image:
        pullPolicy: 'Always'

      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: home
            mountPath: /home/jovyan
            subPath: "uscentral1b/{username}"
      extraEnv:
        # Scratch storage within the cluster
        PANGEO_SCRATCH_PREFIX: "gs://pangeo-scratch"

      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "uscentral1b/{username}"
      cloudMetadata:
        enabled: true
    prePuller:
      continuous:
        enabled: false
    hub:
      resources:
        requests:
          cpu: "0.25"
          memory: 0.5Gi
        limits:
          cpu: "1.25"
          memory: 1Gi

      services:
        mlflow:
          admin: True
          url: mlflow

      extraConfig:
        administrators: |
          c.Authenticator.admin_users = ["TomAugspurger"]
        image_pulls: |
          c.KubeSpawner.start_timeout = 60 * 10  # 10-minute timeout for large image pulls
        profile_list: |
          c.KubeSpawner.profile_list = [
            {
                'display_name': 'Small (1 GB - 4 GB)',
                'default': 'True',
                'kubespawner_override': {
                    'cpu_limit': 2,
                    'cpu_guarantee': 0.3,
                    'mem_limit': '4G',
                    'mem_guarantee': '1G',
                }
            },
            {
                'display_name': 'Medium (4 GB - 8G GB)',
                'kubespawner_override': {
                    'cpu_limit': 2,
                    'cpu_guarantee': 1,
                    'mem_limit': '8G',
                    'mem_guarantee': '4G',
                }
            },
            {
                'display_name': 'Large (12 GB - 16 GB)',
                'kubespawner_override': {
                    'cpu_limit': 4,
                    'cpu_guarantee': 1,
                    'mem_limit': '16G',
                    'mem_guarantee': '12G',
                }
            },
            {
                'display_name': 'ML Image - Large (12 GB - 16 GB)',
                'description': "https://github.com/pangeo-data/pangeo-docker-images/tree/master/ml-notebook",
                'kubespawner_override': {
                    'image': 'pangeo/ml-notebook:master',
                    'cpu_limit': 2,
                    'cpu_guarantee': 1,
                    'mem_limit': '16G',
                    'mem_guarantee': '12G',
                }
            },
          ]

        customPodHook: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'Pangeo Cloud',
            'pangeo_hub_subtitle': 'us-central1-b.gcp.pangeo.io',
            'pangeo_welcome': """Welcome to Pangeo Cloud. This hub lives in Google Cloud region <code>us-central1-b</code>. For information and signup instructions, please visit the <a href="http://pangeo.io/cloud.html">Pangeo Cloud Website</a>.""",
          }

      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
            revision: "39962614b3df4ca86efb29712f7e67c51308d25b"
      extraVolumeMounts:
        - mountPath: /usr/local/share/jupyterhub/custom_templates
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/templates"
        - mountPath: /usr/local/share/jupyterhub/static/extra-assets
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/extra-assets"
      extraEnv:
        OAUTH2_AUTHORIZE_URL: "https://pangeo.auth0.com/authorize"
        OAUTH2_TOKEN_URL: "https://pangeo.auth0.com/oauth/token"
        OAUTH_CALLBACK_URL: "https://staging.us-central1-b.gcp.pangeo.io/hub/oauth_callback"

    auth:
      type: custom
      custom:
        className: oauthenticator.generic.GenericOAuthenticator
        config:
          login_service: "Pangeo"
          token_url: https://pangeo.auth0.com/oauth/token
          userdata_url: https://pangeo.auth0.com/oauth/userinfo
          userdata_method: GET
          username_key: nickname
          scope:
            - openid
            - profile
            - email
      admin:
        access: true
        users:
          - jhamman
          - rabernat
          - TomAugspurger
          - scottyhq

  dask-gateway:
    gateway:
      backend:
        worker:
          extraPodConfig:
            tolerations:
              - key: "cloud.google.com/gke-preemptible"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"

homeDirectories:
  nfs:
    enabled: true
    serverPath: "/homes"
    # Output from `gcloud filestore instances describe pangeo-uscentral1b --zone=us-central1-b`
    serverIP: 10.126.142.50
    serverName: home


# prometheus-operator configuration.
# We set the affinity here in common. staging handles most of the
# rest of the configuartion (domain, IP addresses, etc.)
prometheus-operator:
  prometheusOperator:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core
  grafana:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core
  prometheus:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core
  kube-state-metrics:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core

ingress-nginx:
  controller:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core
