pangeo:
  jupyterhub:
    # proxy:
    #   https:
    #     hosts:
    #       - prod.us-central1-b.gcp.pangeo.io
    #     letsencrypt:
    #       contactEmail: rpa@ldeo.columbia.edu 
    #   service:
    #     loadBalancerIP: 34.69.173.244
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-us-central1b-prod-dask-gateway.prod"
      service:
        # Just in prod to avoid possible port contention.
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/path: '/hub/metrics'

    singleuser:
      extraEnv:
        # TODO: DNS
        DASK_GATEWAY__ADDRESS: "https://prod.us-central1-b.gcp.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-us-central1b-prod-dask-gateway.prod:80"
