name: root
channels:
  - conda-forge
dependencies:
  - jupyterhub
  - bokeh
  - bqplot
  - click
  - cython
  - cytoolz
  - dask=0.19.4
  - dask-ml=0.10.0
  - dask-kubernetes=0.5.0
  - datashader
  - distributed=1.23.3
  - esmpy
  - fastparquet
  - fusepy
  - holoviews
  - gcsfs
  - geoviews
  - hvplot
  - intake::intake-xarray
  - ipywidgets
  - ipyleaflet
  - jedi
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - holoviews
  - libsodium
  - lz4
  - matplotlib
  - msgpack-python
  - nb_conda_kernels
  - nbserverproxy
  - netcdf4
  - nomkl
  - numba
  - numcodecs
  - numpy
  - pandas
  - panel
  - python-blosc
  - python-graphviz
  - pyzmq
  - rasterio
  - s3fs
  - scipy
  - scikit-image
  - scikit-learn
  - toolz
  - tornado=5.0.2
  - xesmf
  - xgcm
  - zarr
  - zict
  - pip:
    - git+https://github.com/pydata/xarray.git
