# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - aws-uswest2.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu
    hub:
      service:
        loadBalancerIP: aa19367a4573811e9a9ef06d2bcc51c9-1125496385.us-west-2.elb.amazonaws.com
    auth:
      github:
        callbackUrl: "https://aws-uswest2.pangeo.io/hub/oauth_callback"
