# Leave commented for first build, then uncomment and add loadBalancerIP
daskhub:
  jupyterhub:
    hub:
      # Reduce requests on staging hub since it is rarely used!
      resources:
        requests:
          cpu: 0
          memory: 0G
        limits:
          cpu: 0.5
          memory: 1G
      extraEnv:
        OAUTH_CALLBACK_URL: "https://staging.aws-uswest2.pangeo.io/hub/oauth_callback"
    singleuser:
      profileList:
        - display_name: "Default Image"
          description: "https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/icesat2/image/binder/Dockerfile"
        - display_name: "Staging Pangeo-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/tree/master/pangeo-notebook"
          kubespawner_override:
            image: pangeo/pangeo-notebook:master
        - display_name: "Latest Pangeo-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/releases"
          kubespawner_override:
            image: pangeo/pangeo-notebook:latest
        - display_name: "Staging Base-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/tree/master/base-notebook"
          kubespawner_override:
            image: pangeo/base-notebook:master
        - display_name: "Staging ML-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/tree/master/ml-notebook"
          kubespawner_override:
            image: pangeo/ml-notebook:master
            mem_limit: 60G
            mem_guarantee: 25G
            environment: {'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility'}
            tolerations: [{'key': 'nvidia.com/gpu','operator': 'Equal','value': 'present','effect': 'NoSchedule'}]
            extra_resource_limits: {"nvidia.com/gpu": "1"}
        - display_name: "ICESat-2 Hackweek 2020"
          description: "https://github.com/ICESAT-2HackWeek/jupyter-image-2020"
          kubespawner_override:
            image: uwhackweeks/icesat2:latest
    proxy:
      https:
        hosts:
          - staging.aws-uswest2.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu

  dask-gateway:
    gateway:
      backend:
        # Ensure the scheduler and worker pods end up on
        # nodes that are already being used, to avoid scheduling on nodes
        # that would otherwise be reclaimed by the cluster autoscaler.
        scheduler:
          extraPodConfig:
            schedulerName: icesat2-staging-user-scheduler
        worker:
          extraPodConfig:
            schedulerName: icesat2-staging-user-scheduler
