# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    hub:
      # Reduce requests on staging hub since it is rarely used!
      resources:
        requests:
          cpu: 0
          memory: 0G
        limits:
          cpu: 0.5
          memory: 1G
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: http://web-public-icesat2-staging-dask-gateway
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "http://web-public-icesat2-staging-dask-gateway/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "tls://scheduler-icesat2-staging-dask-gateway:8786"
        DASK_GATEWAY__AUTH_TYPE: "jupyterhub"
    proxy:
      https:
        hosts:
          - staging.aws-uswest2.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu
    auth:
      github:
        callbackUrl: "https://staging.aws-uswest2.pangeo.io/hub/oauth_callback"
