# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.aws-uswest2.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu
    hub:
      service:
        loadBalancerIP: a070b2175523111e9924302ea5ee1624-1148941357.us-west-2.elb.amazonaws.com
    auth:
      github:
        callbackUrl: "https://staging.aws-uswest2.pangeo.io/hub/oauth_callback"
