name: pangeo
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==0.0.2
  - conda>=4.6.8
  - python=3.7
  - numpy
  - matplotlib
  - xarray>0.10.9
  - ipyleaflet
  - seaborn
  - cartopy
  - pandas
  - geopandas
  - hvplot
  - netCDF4
  - bokeh
  - pip:
    - git+https://github.com/arbennett/pysumma.git@706a69f1ff3a8e910ea574e133cd12a434290152
    - hs_restclient
