# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - nasa.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu
      service:
        loadBalancerIP: a3addbd7967b511e9aa8d024800b3463-1535357642.us-east-1.elb.amazonaws.com
    auth:
      github:
        callbackUrl: "https://nasa.pangeo.io/hub/oauth_callback"
