# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    proxy:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: hub
      https:
        hosts:
        - staging.nasa.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu
      service:
        loadBalancerIP: a7e74bdca654d11e9aa8d024800b3463-192714893.us-east-1.elb.amazonaws.com
    auth:
      github:
        callbackUrl: "https://staging.nasa.pangeo.io/hub/oauth_callback"
