pangeo:
  jupyterhub:
    proxy:
      https:
        enabled: true
        hosts:
          - hub.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
    hub:
      service:
        loadBalancerIP: 35.238.205.43
