pangeo:
  jupyterhub:
    proxy:
      https:
        enabled: true
        hosts:
          - hub.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
      service:
        loadBalancerIP: 35.238.205.43

    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hub.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-dev-prod-dask-gateway.dev-prod:80"
        OAUTH_CALLBACK_URL: "https://hub.pangeo.io/hub/oauth_callback"
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-dev-prod-dask-gateway.dev-prod"
