name: notebook
channels:
  - conda-forge
dependencies:
  - pangeo-notebook=2020.05.04
  - ipykernel
  - nb_conda_kernels
  - fsspec
  - s3fs
  - gcsfs
  - intake
  - intake-stac
  - intake-xarray
  - xarray
  - zarr
  - h5py
  - h5netcdf
  - matplotlib-base
  - ipywidgets
  - libgdal
  - boto3
  - awscli
  - hvplot
  - geoviews
  - panel
  - ipyleaflet
  - datashader
  - requests
  - pandas
  - geopandas
  - rasterio
  - rio-cogeo
  - sat-search
  - sat-stac
  - pip
